services:
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    ports:
      - "5433:5432"  # Changed to avoid conflicts
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      retries: 20
    networks:
      - foglio_network
  foglio:
    image: cosmtrek/air
    working_dir: /foglio/
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./:/foglio/
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - foglio_network
networks:
  foglio_network:
    driver: bridge
volumes:
  storage_data:

