services:
  foglio:
    container_name: foglio
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./:/foglio/
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - foglio_network
networks:
  foglio_network:
    driver: bridge
volumes:
  storage_data:

